
services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: hms-api
    ports:
      - "8080:8080"
    environment:
      - ENV=local
    volumes:
      - ./pb_migrations:/pb/pb_migrations
      - ./pb_hooks:/pb/pb_hooks
      - ./pb_data:/pb/pb_data
    networks:
      - hmsapi

networks:
  hmsapi:
    name: hmsapi
    driver: bridge
